### ISSUE TITLE
It does not work like expected

### ISSUE THREAD

**Issue by ChiyoDragon** [huntresslabs/log4shell-tester#1]
Hey there,

I tried this application and also the website itself, but I never get an response....I checked it against a definitve vulnerable log4j server....but it does not work like it should. 

Also for running it without main class I had to use following command:
`java -cp target/log4shell-jar-with-dependencies.jar com.huntresslabs.log4shell.App hostname 82 83`

**Comment by JohnHammond** [comment]
Hi @ChiyoDragon ,
I saw you had closed this issue just as I was getting on keyboard to check in. Was your problem resolved? Can I ask what the resolution is so it might better help others that find this issue? Can I ask what application you were testing?

**Comment by ChiyoDragon** [comment]
@JohnHammond 
I had to use also nginx-reverse proxy to use it correctly, but it was my fault. Maybe you can add a hint regarding the "wrong" call of the class in java
