### ISSUE TITLE
Error: Could not find or load main class com.huntresslabs.log4shell.App

### ISSUE THREAD

**Issue by mulrus** [huntresslabs/log4shell-tester#12]
Hi folks. Whem I am running the jar
`java -jar log4shell-jar-with-dependencies.jar --help`

After running I see the message
`Error: Could not find or load main class com.huntresslabs.log4shell.App`

Any ideas?

**Comment by calebstewart** [comment]
Hmmm that's odd. Just to verify, you have the newest version (e.g. nothing new with `git pull`)?

Were there any warnings during compilation? Can you upload the JAR file here?

**Comment by mulrus** [comment]
Hello it seems I solved. Sorry for that stuck.

I saw in the log-file, that I forgot to save src folder to compiler and in the log file said that skipping that. 

Now everything is ok Log4shell class included and jar-file works ok.
